on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

       # Make Repo name lowercase for Docker
      - id: repo
        uses: ASzc/change-string-case-action@v2
        with:
         string: ${{github.repository}}
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
            registry: ghrc.io
            username: ${{ github.actor }}
            password: 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
      
      - name: Build Docker Image and push to GitHub Registry
        uses: docker/build-push-action@v2
        with:
            context: .
            tags: ghcr.io/${{ steps.repo.outputs.lowercase }}:latest
            push: ${{ github.ref == 'refs/heads/main'}}
            cache-from: type=registry,ref=${{ steps.repo.outputs.lowercase }}:latest
            cache-to: type=inline

