on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

        # Make Repo name lowercase for Docker
      - id: repo
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{github.repository}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      

      - name: Build Docker Image and push to GitHub Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ghcr.io/${{ steps.repo.outputs.lowercase }}:latest
          push: ${{ github.ref == 'refs/heads/main'}}
