on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

        # Make Repo name lowercase for Docker
      - id: repo
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{github.repository}}
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/${{github.actor}}/rss-parser-website:latest
          docker push ghcr.io/${{github.actor}}/rss-parser-website:latest
